"""initial: users and oauth_tokens

Revision ID: 95a506f3fdea
Revises: 4e4d232c2dee
Create Date: 2026-08-03 12:12:12.690141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95a506f3fdea'
down_revision: Union[str, Sequence[str], None] = '4e4d232c2dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
