"""add provider_username to oauth_tokens

Revision ID: 9fbc0c47823a
Revises: 1e60a7653f88
Create Date: 2026-08-03 18:17:48.364417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fbc0c47823a'
down_revision: Union[str, Sequence[str], None] = '1e60a7653f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_tokens', sa.Column('provider_username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_tokens', 'provider_username')
    # ### end Alembic commands ###
